"""secretmissionupdate

Revision ID: 021ac8894cc5
Revises: f73b7d513bf1
Create Date: 2025-08-27 13:55:46.322794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '021ac8894cc5'
down_revision = 'f73b7d513bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secret_missions', schema=None) as batch_op:
        batch_op.drop_column('sex')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secret_missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sex', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
