"""PriorityRange

Revision ID: 5a38c268d004
Revises: 99fb11034936
Create Date: 2025-08-17 16:45:48.008934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a38c268d004'
down_revision = '99fb11034936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
