"""addtargetchallenge

Revision ID: 68648a1fcf6b
Revises: 021ac8894cc5
Create Date: 2025-08-27 17:05:10.449751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68648a1fcf6b'
down_revision = '021ac8894cc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('target_challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('group_challenge', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('target_challenges', schema=None) as batch_op:
        batch_op.drop_column('group_challenge')
        batch_op.drop_column('player_quantity')

    # ### end Alembic commands ###
