"""RolesIcon

Revision ID: 69db626cebb2
Revises: 5a38c268d004
Create Date: 2025-08-17 18:34:24.302324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69db626cebb2'
down_revision = '5a38c268d004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
