"""test

Revision ID: 75973235ebdd
Revises: afec7f01e030
Create Date: 2025-08-12 12:14:43.378634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75973235ebdd'
down_revision = 'afec7f01e030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
