"""RolesRestriction

Revision ID: 99fb11034936
Revises: 007f684cc9d9
Create Date: 2025-08-17 16:39:20.435865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99fb11034936'
down_revision = '007f684cc9d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
