"""creating

Revision ID: afec7f01e030
Revises: b0d697688406
Create Date: 2025-08-12 12:10:43.790670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afec7f01e030'
down_revision = 'b0d697688406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('drinking', sa.Boolean(), nullable=False),
    sa.Column('sex', sa.Boolean(), nullable=False),
    sa.Column('smoking', sa.Boolean(), nullable=False),
    sa.Column('partner_friendly', sa.Boolean(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('skipping', sa.Float(), nullable=True),
    sa.Column('voting', sa.Boolean(), nullable=False),
    sa.Column('prize', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenges')
    # ### end Alembic commands ###
