"""baseline

Revision ID: b0d697688406
Revises: 
Create Date: 2025-08-10 17:01:10.118409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d697688406'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('drinking', sa.Boolean(), nullable=False),
    sa.Column('sex', sa.Boolean(), nullable=False),
    sa.Column('smoking', sa.Boolean(), nullable=False),
    sa.Column('partner_friendly', sa.Boolean(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('skipping', sa.Float(), nullable=True),
    sa.Column('voting', sa.Boolean(), nullable=False),
    sa.Column('prize', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('title')
    )
    op.create_table('group_challenges',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('drinking', sa.Boolean(), nullable=False),
    sa.Column('sex', sa.Boolean(), nullable=False),
    sa.Column('smoking', sa.Boolean(), nullable=False),
    sa.Column('partner_friendly', sa.Boolean(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('skipping', sa.Float(), nullable=True),
    sa.Column('voting', sa.Boolean(), nullable=False),
    sa.Column('prize', sa.Integer(), nullable=False),
    sa.Column('player_quantity', sa.Integer(), nullable=False),
    sa.Column('teams', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('title')
    )
    op.create_table('secret_missions',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('drinking', sa.Boolean(), nullable=False),
    sa.Column('sex', sa.Boolean(), nullable=False),
    sa.Column('smoking', sa.Boolean(), nullable=False),
    sa.Column('partner_friendly', sa.Boolean(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('prize', sa.Integer(), nullable=False),
    sa.Column('punishment', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secret_missions')
    op.drop_table('group_challenges')
    op.drop_table('challenges')
    # ### end Alembic commands ###
