"""malesAndFemalesInChallenge

Revision ID: df24569af4bc
Revises: 69db626cebb2
Create Date: 2025-08-20 17:22:07.675450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df24569af4bc'
down_revision = '69db626cebb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('males', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('females', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_column('females')
        batch_op.drop_column('males')

    # ### end Alembic commands ###
